# Generated by Django 2.1.1 on 2018-09-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=59)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('employee_id', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('team_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('working_area', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
